import "styles/globals.css"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { twMerge } from "tailwind-merge"

const customFont = Inter({ subsets: ["latin"], variable: "--custom-font" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={twMerge(`${customFont.variable} font-sans`,)}>
      <body className={"min-w-[320px]"}>
      {children}
      </body>
    </html>
  )
}
